version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /app/entrypoint.sh
    volumes:
      - .:/app
      - ./logs:/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - db_replica
    env_file:
      - .env
    networks:
      - app_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app_network

  db_replica:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      REPLICATION_ROLE: replica
      PRIMARY_HOST: db
      PRIMARY_PORT: 5432
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
    depends_on:
      - db
    networks:
      - app_network
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  
  
  celery:
    build:
      context: .
      dockerfile: DockerfileCeleryWorker
    volumes:
      - ./logs:/logs
    depends_on:
      - redis
      - db
      - web


  stripe:
    build:
      context: ./stripe-cli-custom
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - .:/app
      - ./stripe-cli-custom/stripe-token:/root/.config/stripe
    depends_on:
      - web
    env_file:
      - .env
    networks:
      - app_network

volumes:
  postgres_data:
  postgres_replica_data:

networks:
  app_network:
    driver: bridge