# Generated by Django 5.2 on 2025-04-29 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_created_at'),
        ('orders', '0002_order_orders_orde_custome_59b6fb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['customer'], name='chats_chat_custome_9d229b_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['executor'], name='chats_chat_executo_923b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat'], name='chats_messa_chat_id_0c8f01_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user'], name='chats_messa_user_id_b18eea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='chats_messa_created_8b0743_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['read_at'], name='chats_messa_read_at_bbcf91_idx'),
        ),
    ]
