# Generated by Django 5.2 on 2025-04-29 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user'], name='subscriptio_user_id_586440_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_type'], name='subscriptio_subscri_e0999b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='subscriptio_expires_53ce37_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontype',
            index=models.Index(fields=['name'], name='subscriptio_name_0f49d2_idx'),
        ),
    ]
